import { NgModule } from "@angular/core";
import {
	MatButtonModule,
	MatCardModule,
	MatCheckboxModule,
	MatChipsModule,
	MatDatepickerModule,
	MatDialogModule,
	MatExpansionModule,
	MatGridListModule,
	MatIconModule,
	MatInputModule,
	MatListModule,
	MatMenuModule,
	MatNativeDateModule,
	MatOptionModule,
	MatPaginatorModule,
	MatProgressBarModule,
	MatRadioModule,
	MatSelectModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSnackBarModule,
	MatSortModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule
} from "@angular/material";
import { CdkTableModule } from "@angular/cdk/table";

@NgModule({
	imports: [
		MatButtonModule,
		MatSnackBarModule,
		MatCheckboxModule,
		MatSelectModule,
		MatOptionModule,
		MatInputModule,
		MatMenuModule,
		MatTooltipModule,
		MatIconModule,
		MatToolbarModule,
		MatSidenavModule,
		MatDialogModule,
		MatCardModule,
		MatListModule,
		MatTableModule,
		MatPaginatorModule,
		MatSortModule,
		CdkTableModule,
		MatGridListModule,
		MatSlideToggleModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatTabsModule,
		MatProgressBarModule,
		MatRadioModule,
		MatExpansionModule,
		MatChipsModule
	],
	exports: [
		MatButtonModule,
		MatSnackBarModule,
		MatCheckboxModule,
		MatSelectModule,
		MatOptionModule,
		MatInputModule,
		MatMenuModule,
		MatTooltipModule,
		MatIconModule,
		MatToolbarModule,
		MatSidenavModule,
		MatDialogModule,
		MatCardModule,
		MatListModule,
		MatTableModule,
		MatPaginatorModule,
		MatSortModule,
		CdkTableModule,
		MatGridListModule,
		MatSlideToggleModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatTabsModule,
		MatProgressBarModule,
		MatRadioModule,
		MatExpansionModule,
		MatChipsModule
	],
	declarations: []
})

export class MaterialModule {
}
