import { Component } from "@angular/core";
import { UserSettingsService } from "../../shared/services/user-settings/user-settings.service";
import { MatDialog } from "@angular/material/dialog";
import { MatSnackBar } from "@angular/material/snack-bar";
import { SyncService } from "../../shared/services/sync/sync.service";
import { AthleteService } from "../../shared/services/athlete/athlete.service";
import { AdvancedMenuComponent } from "../advanced-menu.component";
import { ConfirmDialogDataModel } from "../../shared/dialogs/confirm-dialog/confirm-dialog-data.model";
import { ConfirmDialogComponent } from "../../shared/dialogs/confirm-dialog/confirm-dialog.component";
import { ElectronService } from "../../shared/services/electron/electron.service";

@Component({
	selector: "app-advanced-menu",
	template: `
		<mat-card>
			<mat-card-content>
				<div>
					In case of problem with the app this section might help you.
				</div>
				<div>
					<button mat-stroked-button color="primary" (click)="onSyncedBackupClear()">Delete athlete's activities</button>
				</div>
				<div>
					<button mat-stroked-button color="primary" (click)="onUserSettingsReset()">Reset athlete & global settings</button>
				</div>
				<div>
					<button mat-stroked-button color="primary" (click)="openLogFile()">Open log file</button>
				</div>
				<div>
					<button mat-stroked-button color="primary" (click)="openAppDataFolder()">Open application data folder</button>
				</div>
				<div>
					<button mat-stroked-button color="primary" (click)="onFullAppReset()">Application reset</button>
				</div>
				<div>
					If problem still persist, consider uninstall/install the app or report a bug.
				</div>
			</mat-card-content>
		</mat-card>
	`,
	styles: [
			`
			button {
				width: 300px;
			}

			div {
				padding-top: 10px;
				padding-bottom: 10px;
			}
		`
	]
})
export class DesktopAdvancedMenuComponent extends AdvancedMenuComponent {

	constructor(public userSettingsService: UserSettingsService,
				public athleteService: AthleteService,
				public syncService: SyncService<any>,
				public electronService: ElectronService,
				public dialog: MatDialog,
				public snackBar: MatSnackBar) {
		super(userSettingsService, athleteService, syncService, dialog, snackBar);
	}

	public onUserSettingsReset(): void {

		const data: ConfirmDialogDataModel = {
			title: "Reset settings",
			content: "This will reset your settings to defaults including: dated athlete settings and global settings. Are you sure to perform this action?"
		};

		const dialogRef = this.dialog.open(ConfirmDialogComponent, {
			minWidth: ConfirmDialogComponent.MIN_WIDTH,
			maxWidth: ConfirmDialogComponent.MAX_WIDTH,
			data: data
		});

		const afterClosedSubscription = dialogRef.afterClosed().subscribe((confirm: boolean) => {
			if (confirm) {
				Promise.all([
					this.userSettingsService.reset(),
					this.athleteService.resetSettings()
				]).then(() => {
					this.snackBar.open("Settings have been reset", "Close");
					afterClosedSubscription.unsubscribe();
				});
			}
		});
	}

	public onFullAppReset(): void {

		const data: ConfirmDialogDataModel = {
			title: "App reset",
			content: "This will completely delete all the data generated by the application to reach a \"fresh install\" state. Are you sure to perform this action?"
		};

		const dialogRef = this.dialog.open(ConfirmDialogComponent, {
			minWidth: ConfirmDialogComponent.MIN_WIDTH,
			maxWidth: ConfirmDialogComponent.MAX_WIDTH,
			data: data
		});

		dialogRef.afterClosed().subscribe((confirm: boolean) => {
			if (confirm) {
				this.electronService.clearAppDataAndRestart();
			}
		});
	}

	public openLogFile(): void {
		this.electronService.openLogFile();
	}

	public openAppDataFolder(): void {
		this.electronService.openAppDataFolder();
	}

	public onZoneSettingsReset(): void {
		throw new Error("Method onZoneSettingsReset not implemented.");
	}
}
