var userSettings = {
    extensionHasJustUpdated: false,
    userGender: 'men',
    userMaxHr: 190,
    userRestHr: 65,
    userFTP: null,
    remoteLinks: true,
    feedAutoScroll: true,
    defaultLeaderboardFilter: 'overall',
    activateRunningGradeAdjustedPace: true,
    activateRunningHeartRate: true,
    activityGoogleMapType: 'terrain',
    hidePremiumFeatures: true,
    displayShopHeaderLink: true,
    displaySegmentRankPercentage: true,
    displayNearbySegments: true,
    displayMotivationScore: true,
    displayActivityRatio: true,
    displayAdvancedPowerData: true,
    displayAdvancedSpeedData: true,
    displayAdvancedHrData: true,
    displayPedalingData: true,
    displayBikeOdoInActivity: true,
    feedHideChallenges: false,
    feedHideCreatedRoutes: false,
    highLightStravaPlusFeature: false,
};
